# Generated by Django 3.1 on 2020-08-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nb_views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
